//! Internal proc-macro crate for `dynoffsets`.
//!
//! Do not use directly — depend on `dynoffsets` instead.

use proc_macro::TokenStream;
use proc_macro2::TokenStream as TokenStream2;
use quote::quote;
use syn::{
    parse::{Parse, ParseStream},
    parse_macro_input, Expr, Item, ItemConst, ItemMod, LitBool, LitStr, Token,
};

struct Args {
    dll: String,
    enabled: bool,
}

impl Default for Args {
    fn default() -> Self {
        Args { dll: "client.dll".to_string(), enabled: true }
    }
}

impl Parse for Args {
    fn parse(input: ParseStream) -> syn::Result<Self> {
        let mut args = Args::default();
        if input.is_empty() {
            return Ok(args);
        }
        let mut first = true;
        while !input.is_empty() {
            if !first {
                input.parse::<Token![,]>()?;
            }
            first = false;
            let lookahead = input.lookahead1();
            if lookahead.peek(LitStr) {
                let s: LitStr = input.parse()?;
                args.dll = s.value();
            } else if lookahead.peek(LitBool) {
                let b: LitBool = input.parse()?;
                args.enabled = b.value;
            } else {
                return Err(lookahead.error());
            }
        }
        Ok(args)
    }
}

/// `#[schema]` / `#[schema("client.dll")]` / `#[schema(false)]`
///
/// Rewrites every `pub const NAME: usize = LIT;` inside the module into a
/// `pub fn NAME() -> usize` that returns the runtime schema offset (if the
/// walker succeeds) or the literal fallback.
#[proc_macro_attribute]
pub fn schema(attr: TokenStream, item: TokenStream) -> TokenStream {
    let args = parse_macro_input!(attr as Args);
    let mut module = parse_macro_input!(item as ItemMod);
    rewrite_schema_module(&mut module, &args);
    quote!(#module).into()
}

fn rewrite_schema_module(class_mod: &mut ItemMod, args: &Args) {
    let Some((_, items)) = class_mod.content.as_mut() else { return };
    let class_name = class_mod.ident.to_string();
    let dll = &args.dll;
    let enabled = args.enabled;

    for item in items.iter_mut() {
        let Item::Const(c) = item else { continue };
        if !is_pub_usize(c) {
            continue;
        }

        let fn_name = c.ident.clone();
        let vis = c.vis.clone();
        let lit_expr = expr_tokens(&c.expr);
        let class_str = LitStr::new(&class_name, c.ident.span());
        let field_str = LitStr::new(&fn_name.to_string(), c.ident.span());

        let new_fn: TokenStream2 = if enabled {
            quote! {
                // code generated by https://github.com/H0llyW00dzZ/dynoffsets — do not edit
                #vis fn #fn_name() -> usize {
                    ::dynoffsets::lookup_or_fallback(#dll, #class_str, #field_str, #lit_expr)
                }
            }
        } else {
            quote! {
                // code generated by https://github.com/H0llyW00dzZ/dynoffsets — do not edit
                #vis fn #fn_name() -> usize { #lit_expr }
            }
        };
        *item = syn::parse2(new_fn).expect("fn");
    }
}

/// `#[globals]`
///
/// Turns `pub const NAME: usize = LIT;` into a function that returns the
/// live pointer from `RuntimeGlobals` (in the `dynoffsets` crate) or the literal if discovery failed.
#[proc_macro_attribute]
pub fn globals(_attr: TokenStream, item: TokenStream) -> TokenStream {
    let mut module = parse_macro_input!(item as ItemMod);
    rewrite_globals_module(&mut module);
    quote!(#module).into()
}

fn rewrite_globals_module(module: &mut ItemMod) {
    let Some((_, items)) = module.content.as_mut() else { return };
    for item in items.iter_mut() {
        let Item::Const(c) = item else { continue };
        if !is_pub_usize(c) {
            continue;
        }

        let fn_name = c.ident.clone();
        let vis = c.vis.clone();
        let lit_expr = expr_tokens(&c.expr);

        let new_fn: TokenStream2 = quote! {
            // code generated by https://github.com/H0llyW00dzZ/dynoffsets — do not edit
            #[inline]
            #vis fn #fn_name() -> usize {
                ::dynoffsets::get_runtime_globals().and_then(|g| g.#fn_name).unwrap_or(#lit_expr)
            }
        };
        *item = syn::parse2(new_fn).expect("fn");
    }
}

/// `#[interfaces]` / `#[interfaces("server.dll")]` / `#[interfaces(false)]`
///
/// Rewrites interface name constants into functions returning the live
/// `CreateInterface` instance pointer or the fallback literal.
#[proc_macro_attribute]
pub fn interfaces(attr: TokenStream, item: TokenStream) -> TokenStream {
    let args = parse_macro_input!(attr as Args);
    let mut module = parse_macro_input!(item as ItemMod);
    rewrite_interfaces_module(&mut module, &args);
    quote!(#module).into()
}

fn rewrite_interfaces_module(module: &mut ItemMod, args: &Args) {
    let Some((_, items)) = module.content.as_mut() else { return };
    let dll = &args.dll;
    let enabled = args.enabled;

    for item in items.iter_mut() {
        let Item::Const(c) = item else { continue };
        if !is_pub_usize(c) {
            continue;
        }

        let fn_name = c.ident.clone();
        let vis = c.vis.clone();
        let lit_expr = expr_tokens(&c.expr);
        let name_str = LitStr::new(&fn_name.to_string(), c.ident.span());

        let new_fn: TokenStream2 = if enabled {
            quote! {
                // code generated by https://github.com/H0llyW00dzZ/dynoffsets — do not edit
                #[inline]
                #vis fn #fn_name() -> usize {
                    ::dynoffsets::get_runtime_interfaces()
                        .and_then(|i| i.get(#dll, #name_str))
                        .unwrap_or(#lit_expr)
                }
            }
        } else {
            quote! {
                // code generated by https://github.com/H0llyW00dzZ/dynoffsets — do not edit
                #[inline] #vis fn #fn_name() -> usize { #lit_expr }
            }
        };
        *item = syn::parse2(new_fn).expect("fn");
    }
}

/// `#[buttons]`
///
/// Rewrites button name constants into functions returning the address of
/// the button's live `state: u32` field (or the fallback).
#[proc_macro_attribute]
pub fn buttons(_attr: TokenStream, item: TokenStream) -> TokenStream {
    let mut module = parse_macro_input!(item as ItemMod);
    rewrite_buttons_module(&mut module);
    quote!(#module).into()
}

fn rewrite_buttons_module(module: &mut ItemMod) {
    let Some((_, items)) = module.content.as_mut() else { return };
    for item in items.iter_mut() {
        let Item::Const(c) = item else { continue };
        if !is_pub_usize(c) {
            continue;
        }

        let fn_name = c.ident.clone();
        let vis = c.vis.clone();
        let lit_expr = expr_tokens(&c.expr);
        let name_str = LitStr::new(&fn_name.to_string(), c.ident.span());

        let new_fn: TokenStream2 = quote! {
            // code generated by https://github.com/H0llyW00dzZ/dynoffsets — do not edit
            #[inline]
            #vis fn #fn_name() -> usize {
                ::dynoffsets::get_runtime_buttons()
                    .and_then(|b| b.get(#name_str))
                    .unwrap_or(#lit_expr)
            }
        };
        *item = syn::parse2(new_fn).expect("fn");
    }
}

fn is_pub_usize(c: &ItemConst) -> bool {
    matches!(c.vis, syn::Visibility::Public(_))
        && matches!(c.ty.as_ref(), syn::Type::Path(p) if p.path.is_ident("usize"))
}

fn expr_tokens(expr: &Expr) -> TokenStream2 {
    quote!(#expr)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn args_default_is_client_dll_enabled() {
        let a = Args::default();
        assert_eq!(a.dll, "client.dll");
        assert!(a.enabled);
    }

    #[test]
    fn args_parse_empty_uses_defaults() {
        let a: Args = syn::parse_str("").unwrap();
        assert_eq!(a.dll, "client.dll");
        assert!(a.enabled);
    }

    #[test]
    fn args_parse_dll_string() {
        let a: Args = syn::parse_str("\"server.dll\"").unwrap();
        assert_eq!(a.dll, "server.dll");
        assert!(a.enabled);
    }

    #[test]
    fn args_parse_bool_only() {
        let a: Args = syn::parse_str("false").unwrap();
        assert!(!a.enabled);
    }

    #[test]
    fn args_parse_dll_and_bool() {
        let a: Args = syn::parse_str("\"engine2.dll\", false").unwrap();
        assert_eq!(a.dll, "engine2.dll");
        assert!(!a.enabled);
    }

    #[test]
    fn args_parse_two_dlls_last_wins() {
        let a: Args = syn::parse_str("\"a.dll\", \"b.dll\"").unwrap();
        assert_eq!(a.dll, "b.dll");
    }

    #[test]
    fn args_parse_invalid_token_errors() {
        let r: syn::Result<Args> = syn::parse_str("123");
        assert!(r.is_err());
    }

    #[test]
    fn args_parse_missing_comma_errors() {
        let r: syn::Result<Args> = syn::parse_str("\"a.dll\" false");
        assert!(r.is_err());
    }

    #[test]
    fn is_pub_usize_accepts_pub_usize_const() {
        let c: ItemConst = syn::parse_str("pub const X: usize = 1;").unwrap();
        assert!(is_pub_usize(&c));
    }

    #[test]
    fn is_pub_usize_rejects_private_const() {
        let c: ItemConst = syn::parse_str("const X: usize = 1;").unwrap();
        assert!(!is_pub_usize(&c));
    }

    #[test]
    fn is_pub_usize_rejects_non_usize_const() {
        let c: ItemConst = syn::parse_str("pub const X: u32 = 1;").unwrap();
        assert!(!is_pub_usize(&c));
    }

    #[test]
    fn is_pub_usize_rejects_complex_type() {
        let c: ItemConst = syn::parse_str("pub const X: [u8; 4] = [0; 4];").unwrap();
        assert!(!is_pub_usize(&c));
    }

    #[test]
    fn expr_tokens_roundtrip_simple() {
        let e: Expr = syn::parse_str("42").unwrap();
        assert_eq!(expr_tokens(&e).to_string(), "42");
    }

    #[test]
    fn expr_tokens_roundtrip_arith() {
        let e: Expr = syn::parse_str("0x10 + 0x08").unwrap();
        assert!(!expr_tokens(&e).to_string().is_empty());
    }

    fn parse_mod(src: &str) -> ItemMod {
        syn::parse_str(src).unwrap()
    }

    #[test]
    fn rewrite_schema_enabled_emits_lookup_call() {
        let mut m = parse_mod("mod C_Foo { pub const m_x: usize = 0x10; }");
        rewrite_schema_module(&mut m, &Args::default());
        let s = quote!(#m).to_string();
        assert!(s.contains("lookup_or_fallback"));
        assert!(s.contains("\"C_Foo\""));
        assert!(s.contains("\"m_x\""));
    }

    #[test]
    fn rewrite_schema_disabled_emits_literal_fn() {
        let mut m = parse_mod("mod C_Foo { pub const m_x: usize = 0x10; }");
        let args = Args { dll: "client.dll".into(), enabled: false };
        rewrite_schema_module(&mut m, &args);
        let s = quote!(#m).to_string();
        assert!(!s.contains("lookup_or_fallback"));
        assert!(s.contains("fn m_x"));
    }

    #[test]
    fn rewrite_schema_skips_non_pub_usize_items() {
        let mut m = parse_mod(
            "mod C_Foo { const priv_x: usize = 1; pub const non_usize: u32 = 2; \
             pub fn f() {} pub const ok: usize = 0x10; }",
        );
        rewrite_schema_module(&mut m, &Args::default());
        let s = quote!(#m).to_string();
        // exactly one rewritten item (the pub const usize one)
        let count = s.matches("lookup_or_fallback").count();
        assert_eq!(count, 1);
    }

    #[test]
    fn rewrite_schema_handles_module_without_body() {
        // `mod E;` has no inline content → function returns early without touching anything.
        let mut m = parse_mod("mod E;");
        rewrite_schema_module(&mut m, &Args::default());
        rewrite_globals_module(&mut m);
        rewrite_interfaces_module(&mut m, &Args::default());
        rewrite_buttons_module(&mut m);
    }

    #[test]
    fn rewrite_globals_emits_runtime_lookup() {
        let mut m = parse_mod("mod g { pub const dw_thing: usize = 0x42; }");
        rewrite_globals_module(&mut m);
        let s = quote!(#m).to_string();
        assert!(s.contains("get_runtime_globals"));
        assert!(s.contains("dw_thing"));
    }

    #[test]
    fn rewrite_interfaces_enabled_emits_lookup() {
        let mut m = parse_mod("mod i { pub const Source2Client002: usize = 0xAA; }");
        rewrite_interfaces_module(&mut m, &Args::default());
        let s = quote!(#m).to_string();
        assert!(s.contains("get_runtime_interfaces"));
        assert!(s.contains("\"Source2Client002\""));
    }

    #[test]
    fn rewrite_interfaces_disabled_emits_literal() {
        let mut m = parse_mod("mod i { pub const Source2Client002: usize = 0xAA; }");
        let args = Args { dll: "client.dll".into(), enabled: false };
        rewrite_interfaces_module(&mut m, &args);
        let s = quote!(#m).to_string();
        assert!(!s.contains("get_runtime_interfaces"));
    }

    #[test]
    fn rewrite_buttons_emits_runtime_lookup() {
        let mut m = parse_mod("mod b { pub const in_attack: usize = 0x100; }");
        rewrite_buttons_module(&mut m);
        let s = quote!(#m).to_string();
        assert!(s.contains("get_runtime_buttons"));
        assert!(s.contains("\"in_attack\""));
    }

    #[test]
    fn rewrite_globals_skips_non_pub_usize_items() {
        let mut m = parse_mod(
            "mod g { const priv_x: usize = 1; pub const ok: usize = 2; pub const non_usize: u32 = 3; }",
        );
        rewrite_globals_module(&mut m);
        let s = quote!(#m).to_string();
        assert_eq!(s.matches("get_runtime_globals").count(), 1);
    }

    #[test]
    fn rewrite_interfaces_skips_non_pub_usize_items() {
        let mut m = parse_mod(
            "mod i { const priv_x: usize = 1; pub const ok: usize = 2; pub const non_usize: u32 = 3; }",
        );
        rewrite_interfaces_module(&mut m, &Args::default());
        let s = quote!(#m).to_string();
        assert_eq!(s.matches("get_runtime_interfaces").count(), 1);
    }

    #[test]
    fn rewrite_buttons_skips_non_pub_usize_items() {
        let mut m = parse_mod(
            "mod b { const priv_x: usize = 1; pub const ok: usize = 2; pub const non_usize: u32 = 3; }",
        );
        rewrite_buttons_module(&mut m);
        let s = quote!(#m).to_string();
        assert_eq!(s.matches("get_runtime_buttons").count(), 1);
    }

    #[test]
    fn rewrite_modules_with_empty_body_are_unchanged() {
        let mut m = parse_mod("mod empty {}");
        rewrite_schema_module(&mut m, &Args::default());
        rewrite_globals_module(&mut m);
        rewrite_interfaces_module(&mut m, &Args::default());
        rewrite_buttons_module(&mut m);
        let s = quote!(#m).to_string();
        assert!(s.contains("mod empty"));
    }
}
